# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    rate_limiter:
        parse_upload:
            policy: token_bucket
            limit: '%env(int:DEMO_RATE_LIMIT)%'
            rate: { interval: '1 day' }

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
